### ISSUE TITLE
Skin files wont load?

### ISSUE THREAD

**Issue by Darkstalix** [IgeNiaI/Q-Zandronum#339] opened 2024-07-26 22:15 UTC
Maybe im wrong about it just in case this fork doesnt support it?
I have a skin folder with font files sound wad files etc but they wont load
Qzan doesnt support skin files?

**Comment by IgeNiaI** [comment] 2024-07-26 23:43
I never used skins myself. QZan is a fork of Zandronum 3.0. Did 3.0 support the skins the way you described?
I did some changes related to skins based on modders requests, but that shouldn't break loading the skins.

**Comment by Darkstalix** [comment] 2024-07-27 14:43
Yes on zandronum 3.0 and (and before that) you make a skin folder and you can add some wads to make them work by default without the need to load them. For example i could throw a font.wad there or a flashlight mod and it would load those by default

**Comment by IgeNiaI** [comment] 2024-07-27 14:54
Can you please provide example files and steps on how to reproduce the issue?

**Comment by Darkstalix** [comment] 2024-07-27 15:02
Of course. For example when i play the Ultimate(doom1) i always like playing with the PlayStation version music, I just load up doom with doomseeker and have the file of PSXMUSIC.WAD in the skins folder and immediately plays the psx music instead the original rock metal of the original doom.


https://www.mediafire.com/file/3jcvdnohfvumchu/PSXMUSIC.WAD/file
I hope im allowed to load this wad i have no idea please dont kill me brother :(

Keep in mind those steps are for Zandronum and i tried the same setup on latest Qzan

**Comment by IgeNiaI** [comment] 2024-07-28 01:54
So it's a bug in OpenAL. If you go to settings and switch sound backend to FMOD, the issue gets fixed. I'll look into fixing it for OpenAL.

**Comment by IgeNiaI** [comment] 2024-07-28 02:46
It's something about how OpenAL loads sounds. The WAD you linked is quite special, because it contains mp3 files that have actual mp3 extension, but then they do some WAD format trickery to make the engine think that the file doesn't have this extension. I made a pk3 with exactly same files but without extension, and it works fine.
https://www.mediafire.com/file/wjh0a8jyc71g72s/PSXMUSIC.pk3/file

**Comment by IgeNiaI** [comment] 2024-07-28 02:48
I probably won't fix this cause I barely have time to work on other things, especially now that there is a workaround. Hopefully this gets fixed if/when QZan features will be merged to vanilla Zandro.

**Closed by IgeNiaI** 2024-07-28 02:48 UTC
